<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>dotnet-AiDispatcher.Worker-6da2588c-ffad-40ca-a42f-ace1821272f5</UserSecretsId>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.10"/>
    </ItemGroup>

    <ItemGroup>
      <Content Include="..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Configuration\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\AiDispatcher.Application\AiDispatcher.Application.csproj" />
      <ProjectReference Include="..\AiDispatcher.Infrastructure\AiDispatcher.Infrastructure.csproj" />
    </ItemGroup>
</Project>
